#spring:
#  datasource:
##    url: jdbc:h2:~/test
#    url: jdbc:h2:tcp://localhost/~/test # 메모리 내 데이터베이스 URL
#    driver-class-name: org.h2.Driver # H2 드라이버 클래스
#    username: sa # 기본 사용자 이름
#    password: # 기본 비밀번호는 비워둡니다.
#  h2:
#    console:
#      enabled: true # H2 콘솔을 활성화합니다.
#      path: /h2-console # H2 콘솔의 접근 경로
#  jpa:
#    hibernate:
#      ddl-auto: create # 일단 우리는 스키마 생성해야하니까~
#    properties:
#      dialect: org.hibernate.dialect.H2Dialect
#      hibernate:
#        format_sql: true # 얘는 실제 디비로 나가는 sql을 보여줍니다
#  sql:
#    init:
#      mode: always # 애플리케이션 시작 시 스크립트 초기화 (기본값: embedded)

spring:
  profiles:
    include: SECRET-KEY

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{RDS 엔드포인트}:3306/$db
    username: admin
    password: qlalfqjsgh

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  logging.level:
    org.hibernate.SQL: debug

  # healthcheck
  management:
    endpoints:
      web:
        base-path: # 기본값 /actuator
        path-mapping:
          health: # 기본값 /health
    endpoint:
      health:
        show-details: always